######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 15 22:44:37 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
# Input
HEADERS += main.hh
SOURCES += main.cpp
RESOURCES = resources.qrc
